// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pocketses.Core.DataAccessLayer;

#nullable disable

namespace Pocketses.Core.Migrations;

[DbContext(typeof(PocketsesContext))]
[Migration("20221023195233_Initial")]
partial class Initial
{
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "6.0.10")
            .HasAnnotation("Relational:MaxIdentifierLength", 128);

        SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

        modelBuilder.Entity("Pocketses.Core.Models.Campaign", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTime>("CreatedAtUtc")
                    .HasColumnType("datetime2");

                b.Property<Guid>("CreatedBy")
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("Name")
                    .HasColumnType("nvarchar(max)");

                b.Property<DateTime>("UpdatedAtUtc")
                    .HasColumnType("datetime2");

                b.Property<Guid>("UpdatedBy")
                    .HasColumnType("uniqueidentifier");

                b.HasKey("Id");

                b.ToTable("Campaigns");
            });

        modelBuilder.Entity("Pocketses.Core.Models.Character", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<Guid?>("CampaignId")
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTime>("CreatedAtUtc")
                    .HasColumnType("datetime2");

                b.Property<Guid>("CreatedBy")
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("Name")
                    .HasColumnType("nvarchar(max)");

                b.Property<int?>("PlayerId")
                    .HasColumnType("int");

                b.Property<DateTime>("UpdatedAtUtc")
                    .HasColumnType("datetime2");

                b.Property<Guid>("UpdatedBy")
                    .HasColumnType("uniqueidentifier");

                b.HasKey("Id");

                b.HasIndex("CampaignId");

                b.HasIndex("PlayerId");

                b.ToTable("Characters");
            });

        modelBuilder.Entity("Pocketses.Core.Models.Player", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                b.Property<Guid?>("CampaignId")
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTime>("CreatedAtUtc")
                    .HasColumnType("datetime2");

                b.Property<Guid>("CreatedBy")
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("Name")
                    .HasColumnType("nvarchar(max)");

                b.Property<DateTime>("UpdatedAtUtc")
                    .HasColumnType("datetime2");

                b.Property<Guid>("UpdatedBy")
                    .HasColumnType("uniqueidentifier");

                b.HasKey("Id");

                b.HasIndex("CampaignId");

                b.ToTable("Players");
            });

        modelBuilder.Entity("Pocketses.Core.Models.Character", b =>
            {
                b.HasOne("Pocketses.Core.Models.Campaign", null)
                    .WithMany("Characters")
                    .HasForeignKey("CampaignId");

                b.HasOne("Pocketses.Core.Models.Player", null)
                    .WithMany("Characters")
                    .HasForeignKey("PlayerId");
            });

        modelBuilder.Entity("Pocketses.Core.Models.Player", b =>
            {
                b.HasOne("Pocketses.Core.Models.Campaign", "Campaign")
                    .WithMany("Players")
                    .HasForeignKey("CampaignId");

                b.Navigation("Campaign");
            });

        modelBuilder.Entity("Pocketses.Core.Models.Campaign", b =>
            {
                b.Navigation("Characters");

                b.Navigation("Players");
            });

        modelBuilder.Entity("Pocketses.Core.Models.Player", b =>
            {
                b.Navigation("Characters");
            });
#pragma warning restore 612, 618
    }
}
