version: '3.4'

services:
  pocketses.api:
    container_name: pocketses-api
    image: woutermeuwis/pocketsesapi
    build:
      context: .
      dockerfile: Pocketses.Api/Dockerfile
    #TODO Add volume for db file
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "8000:80"
  
  pocketses.web:
    container_name: pocketses-web
    image: woutermeuwis/pocketsesweb
    build:
      context: ./Pocketses.Web
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    
